//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportBaseEntities1 : DbContext
    {
        public ReportBaseEntities1()
            : base("name=ReportBaseEntities1")
        {
        }
       
    public static ReportBaseEntities1 _context;

    public static ReportBaseEntities1 GetContext()
    {
        if (_context == null)
        {
            _context = new ReportBaseEntities1();
        }
        return _context;
    }
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<report_info> report_info { get; set; }
    }
}
